name: telebot test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  telebot-test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: "3.8"
            delay: 0
          - python-version: "3.9"
            delay: 10
          - python-version: "3.10"
            delay: 20
          - python-version: "3.11"
            delay: 30
          - python-version: "3.12"
            delay: 40
          - python-version: "3.13"
            delay: 50
          - python-version: "3.14"
            delay: 60

    steps:
      - uses: actions/checkout@v4

      - name: Staggered start
        run: |
          # Wait to avoid simultaneous API requests or resource spikes
          echo "[$(date)] Waiting ${{ matrix.delay }} seconds for Python ${{ matrix.python-version }}..."
          sleep ${{ matrix.delay }}
          echo "[$(date)] Waiting completed."

      - name: Initialize and update submodules recursively
        run: git submodule update --init --recursive

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests

      - name: Run tests
        env:
          TEST_RUN: "true"
          BOT_API_TEST_TOKEN: ${{ secrets.BOT_API_TEST_TOKEN }}
        run: |
          python -u test/src/telebot_test.py

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: telebot-python-${{ matrix.python-version }}-log
          path: telebot/data/logs/telebot_telegram_test.log
          overwrite: true
          compression-level: 9
          if-no-files-found: error

      - name: Print log
        if: always()
        run: |
          cat telebot/data/logs/telebot_telegram_test.log
